version: '3.9'

services:
  node:
    build: ./node
    ports:
      - "3000:3000"
    environment:
      - UNLEASH_URL=http://unleash-server:4242/api
      - UNLEASH_API_TOKEN=*:*.unleash-insecure-admin-api-token

  java:
    build: ./java
    ports:
      - "5100:5100"
    environment:
      - PORT=5100
      - UNLEASH_URL=http://unleash-server:4242/api
      - UNLEASH_API_TOKEN=*:*.unleash-insecure-admin-api-token

  python:
    build: ./python
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - UNLEASH_URL=http://unleash-server:4242/api
      - UNLEASH_API_TOKEN=*:*.unleash-insecure-admin-api-token

  unleash-server:
    image: unleashorg/unleash-server:${UNLEASH_SERVER_VERSION:-latest}
    environment:
      DATABASE_HOST: postgres
      DATABASE_NAME: unleash
      DATABASE_USERNAME: unleash_user
      DATABASE_PASSWORD: unleash.the.password
      DATABASE_SSL: false
      INIT_CLIENT_API_TOKENS: "test-server:development.unleash-insecure-api-token"
      INIT_ADMIN_API_TOKENS: "*:*.unleash-insecure-admin-api-token"
      LOG_LEVEL: info
    ports: 
      - 4242:4242
    depends_on:
      - postgres
    volumes:
      - ./server/start-unleash.sh:/start-unleash.sh
    command: /start-unleash.sh

  initializer:
    image: alpine/curl
    depends_on:
      - unleash-server
    volumes:
       - ./server/initial-state.json:/initial-state.json
       - ./server/init.sh:/init.sh
    command: /init.sh

  postgres:
    image: postgres:alpine3.15
    environment:
      POSTGRES_USER: unleash_user
      POSTGRES_PASSWORD: unleash.the.password
      POSTGRES_DB: unleash