# syntax=docker/dockerfile:1

FROM golang:1.19-alpine

WORKDIR /app

COPY go.mod ./
COPY go.sum ./
RUN go mod download

COPY *.go ./

RUN go build -o /sdk-integration-tester

EXPOSE 5010

CMD [ "/sdk-integration-tester" ]
