# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Integration tests

on:
  push:
    branches: [main, gh-action]
  pull_request:
    branches: [main, gh-action]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        server: [ "latest" ]
        sdk: [
          { container: node, port: 3000 },
          { container: java, port: 5100 },
          { container: python, port: 5000 },
        ]

    steps:
      - uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: "npm"
      - run: yarn install
      - name: Setup unleash server
        run: docker compose up -d postgres unleash-server initializer
      - name: Await initialization
        run: ./server/wait-container-exit.sh initializer
      - name: Test ${{ matrix.sdk.container }} with ${{ matrix.server }}
        run: ./server/run-test.sh ${{ matrix.sdk.container}} ${{ matrix.sdk.port}}
      - name: Clean up
        run: docker compose stop postgres unleash-server initializer
