name: Integration tests

on:
  # push:
  pull_request:
  schedule: 
    - cron: '30 5 * * 1-5'

jobs:
  integration:
    runs-on: ubuntu-latest

    strategy:
      max-parallel: 10
      matrix:
        yaml-spec:
          - only-valid
    steps:
      - uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: "npm"
      - run: yarn install
      - name: Test ${{ matrix.yaml-spec }}
        run: CONFIG=${{ matrix.yaml-spec }} yarn test from-config
