# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Integration tests

on:
  push:
    branches: [main, gh-action]
  pull_request:
    branches: [main, gh-action]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        sdk-url:
          [
            "all",
          ]

    steps:
      - uses: actions/checkout@v3
      - name: Test ${{ matrix.sdk-url }}
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: "npm"
      - run: yarn install
      - run: docker version
      - run: docker compose version
      - run: ./run-tests.sh
