# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Integration tests

on:
  push:
  pull_request:
  schedule: 
    - cron: '30 5 * * 1-5'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      matrix:
        server:
          - https://node-sdk-test-server.herokuapp.com
          - https://unleash-java-tester.herokuapp.com
          - https://unleash-python-tester.herokuapp.com
    steps:
      - run: echo "Should cache docker images ${{ matrix.server }}"
  integration:
    runs-on: ubuntu-latest

    strategy:
      max-parallel: 10
      matrix:
        server: 
          - OSSServer
          - MockServer
    steps:
      - uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: "npm"
      - run: yarn install
      - name: Test against ${{ matrix.server }}
        run: SERVER=${{ matrix.server }} yarn test