# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Integration tests

on:
  push:
    branches: [main, gh-action]
  pull_request:
    branches: [main, gh-action]

jobs:
  integration:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        server: [ "latest", "4.14", "4.13"]

    steps:
      - uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: "npm"
      - run: yarn install
      - name: Setup unleash server
        run: UNLEASH_SERVER_VERSION=${{ matrix.server }} docker compose up -d postgres unleash-server initializer
      - name: Await initialization
        run: ./server/wait-container-exit.sh initializer

      - name: Test Node SDK with ${{ matrix.server }}
        run: ./server/run-test.sh node 3000
      - name: Test Python SDK with ${{ matrix.server }}
        run: ./server/run-test.sh python 5000
      - name: Test Java SDK with ${{ matrix.server }}
        run: ./server/run-test.sh java 5100

      - name: Clean up
        run: docker compose stop postgres unleash-server initializer