# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        sdk-url:
          [
            "https://node-sdk-test-server.herokuapp.com",
            "https://unleash-java-tester.herokuapp.com",
            "https://unleash-python-tester.herokuapp.com",
          ]

    steps:
      - uses: actions/checkout@v3
      - name: Test ${{ matrix.sdk-url }}
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: "npm"
      - run: yarn install
      - run: yarn test
        env:
          CI: true,
          SDK_URL: ${{ matrix.sdk-url }}
